baseURL = "https://listrik.bangunan.co/"
languageCode = "id"
title = "Tukang Instalasi Listrik | Pasang Instalasi Listrik Rumah, Kantor, Ruko Berpengalaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jasa Instalasi Listrik dan Tukang Pasang Listrik - Berpengalaman, Profesional, dan Berkualitas"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa instalasi listrik", "pasang listrik rumah", "jasa pasang listrik kantor", "instalasi listrik ruko", "tukang listrik berpengalaman", "jasa listrik murah"]
  base_price = 100000
  price_range = 50000
  free_consultation = true
  service_types = [
  "Instalasi Listrik Rumah",
  "Instalasi Listrik Kantor",
  "Instalasi Listrik Ruko",
  "Perbaikan Instalasi Listrik",
  "Pemasangan Saklar dan Stop Kontak",
  "Pemasangan Panel Listrik"
  ]
  categories = ["Jasa Instalasi Listrik", "Tukang Listrik", "Listrik Rumah dan Kantor"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika instalasi tidak sesuai standar keamanan.",
  "Pengembalian biaya jika hasil instalasi tidak memuaskan.",
  "Perbaikan gratis jika terjadi masalah setelah pemasangan dalam 1 bulan."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Bandung", "Purwakarta", "Serang", "Cikampek", "Subang"]
  service_output = "Instalasi listrik yang aman, rapi, dan sesuai standar."

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Pasang Instalasi Listrik Profesional"
  hero_description = "Kami menawarkan layanan instalasi listrik berkualitas, dengan material dan pengerjaan yang aman serta rapi. Solusi terbaik untuk kebutuhan listrik rumah, kantor, atau ruko Anda, dilakukan oleh tim berpengalaman."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Layanan Instalasi Listrik"

# Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan instalasi listrik dengan bahan berkualitas dan harga terjangkau. Tim kami siap melakukan melayani Anda dengan layanan konsultasi gratis untuk membantu Anda menemukan solusi terbaik sesuai kebutuhan listrik Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "listrik.bangunan.co menawarkan layanan instalasi listrik berkualitas, dengan fokus pada keselamatan, keandalan, dan profesionalisme. Kami berkomitmen memberikan kepuasan pelanggan dengan pemasangan listrik yang aman, cepat, dan efisien. Pilih kami untuk memenuhi kebutuhan listrik rumah, kantor, atau properti Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya menggunakan layanan instalasi listrik dari listrik.bangunan.co untuk {rumah|proyek|gedung|renovasi} saya, dan hasilnya {sangat memuaskan|luar biasa|memenuhi harapan}. {Pemasangannya|Proses instalasinya} {rapi|bersih|teratur} dan sistem listriknya {berkualitas tinggi|tahan lama|handal}.|Layanan listrik.bangunan.co {sangat profesional|berkualitas} dengan hasil yang {rapi|teratur} dan sesuai standar.}"
  response = "{Terima kasih atas {kepercayaannya|pilihan Anda}! Kami senang dapat menyediakan instalasi listrik berkualitas untuk {rumah|proyek} Anda.|Kami {menghargai|berterima kasih atas} kepercayaan Anda. Terima kasih telah memilih layanan kami.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{listrik.bangunan.co sangat {membantu|mempermudah} saya dalam {memilih|menentukan} dan memasang instalasi listrik untuk {rumah|proyek} saya. Hasilnya {sangat memuaskan|luar biasa|memenuhi harapan} dan sesuai dengan {kebutuhan|ekspektasi|rencana} saya.|Saya {sangat puas|terkesan} dengan bantuan listrik.bangunan.co dalam instalasi listrik yang {rapi|teratur} dan sesuai dengan keinginan saya.}"
  response = "{Kami sangat {menghargai|berterima kasih atas} ulasan Anda. Senang mendengar bahwa Anda puas dengan {layanan|pelayanan} dan hasil instalasi listrik kami.|Terima kasih atas ulasannya, kami senang dapat memenuhi harapan Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Instalasi listrik dari listrik.bangunan.co {sangat rapi|bersih|teratur} dan cocok untuk proyek {perumahan|gedung|konstruksi} saya. Proses pemasangan juga {cepat|efisien|profesional}.|Saya {sangat puas|terkesan} dengan instalasi listrik dari listrik.bangunan.co. Hasilnya {rapi|teratur} dan pemasangan berjalan dengan {cepat|profesional|efisien}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan instalasi listrik berkualitas dengan {layanan terbaik|pelayanan prima}.|Kami sangat senang mendengar bahwa Anda puas dengan hasil instalasi listrik dari kami.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan instalasi listrik dari listrik.bangunan.co. {Kualitas|Mutu} pemasangan {sangat baik|terbaik|terjamin} dan tahan lama untuk proyek saya.|Instalasi listrik dari listrik.bangunan.co {berkualitas|handal|kokoh} dengan pemasangan yang {cepat|efisien|rapi} sesuai kebutuhan proyek saya.}"
  response = "{Senang mendengar Anda puas dengan layanan instalasi listrik kami. Terima kasih atas {kepercayaannya|pilihan Anda}!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih layanan kami.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan listrik.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Instalasi listrik yang saya {pasang|gunakan|terapkan} {sangat berkualitas|berkualitas tinggi|bermutu} dan sesuai dengan {harapan|ekspektasi|rencana} saya.|Saya {senang|terkesan|puas} dengan pelayanan dari listrik.bangunan.co. Instalasi listriknya {berkualitas|tahan lama|modern} dan sesuai dengan keinginan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda mewujudkan proyek dengan instalasi listrik terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek Anda kepada kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Instalasi listrik dari listrik.bangunan.co sangat {sesuai|tepat|cocok} dengan kebutuhan proyek {renovasi|rumah|gedung|perumahan} saya. Proses pemasangannya {cepat|aman|efisien} dan {terjamin|rapi|bersih}.|Saya {puas|terkesan|senang} dengan instalasi listrik dari listrik.bangunan.co. Layanan instalasinya {profesional|cepat|teratur} dan sesuai dengan kebutuhan proyek saya.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan hasil instalasi listrik kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan instalasi listrik Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Instalasi Listrik Rumah"
  price = "500.000"
[[params.tabelItems]]
  name = "Instalasi Listrik Kantor"
  price = "750.000"
[[params.tabelItems]]
  name = "Instalasi Listrik Ruko"
  price = "600.000"
[[params.tabelItems]]
  name = "Perbaikan Instalasi Listrik"
  price = "250.000"
[[params.tabelItems]]
  name = "Pemasangan Saklar dan Stop Kontak"
  price = "150.000"
[[params.tabelItems]]
  name = "Pemasangan Panel Listrik"
  price = "1.200.000"
[[params.tabelItems]]
  name = "Membuat Lubang Stop Kontak"
  price = "25.000"
[[params.tabelItems]]
  name = "Membuat Lubang Saklar Single"
  price = "25.000"
[[params.tabelItems]]
  name = "Pembobokan Saklar Seri"
  price = "25.000"
[[params.tabelItems]]
  name = "Pembobokan Outlet Telepon"
  price = "25.000"
[[params.tabelItems]]
  name = "Membuat Lubang Outlet Antena"
  price = "25.000"
[[params.tabelItems]]
  name = "Membuat Lubang Outlet MCB"
  price = "45.000"
[[params.tabelItems]]
  name = "Pemasangan Kabel Listrik"
  price = "65.000"
[[params.tabelItems]]
  name = "Pemasangan Saklar"
  price = "70.000"
[[params.tabelItems]]
  name = "Instalasi Saklar AC"
  price = "100.000"
[[params.tabelItems]]
  name = "Instalasi Stop Kontak Water Heater"
  price = "100.000"
[[params.tabelItems]]
  name = "Pemasangan Lampu"
  price = "100.000"
[[params.tabelItems]]
  name = "Instalasi Lampu Taman"
  price = "140.000"
[[params.tabelItems]]
  name = "Pemasangan Kabel Antena Layar"
  price = "150.000"
[[params.tabelItems]]
  name = "Pemasangan Radar Pompa Air"
  price = "150.000"
[[params.tabelItems]]
  name = "Instalasi Panel MCB Listrik"
  price = "180.000"
[[params.tabelItems]]
  name = "Pemasangan MCB"
  price = "280.000"
[[params.tabelItems]]
  name = "Instalasi Kabel Induk"
  price = "100.000"
[[params.tabelItems]]
  name = "Pasang Lampu Fitting Plafon"
  price = "45.000"
[[params.tabelItems]]
  name = "Pasang Lampu Gantung"
  price = "45.000"
[[params.tabelItems]]
  name = "Pasang Kipas Angin Gantung"
  price = "150.000"
[[params.tabelItems]]
  name = "Pasang Exhaust Fan Dinding/Plafon"
  price = "150.000"
[[params.tabelItems]]
  name = "Pasang Lampu Dinding"
  price = "100.000"
[[params.tabelItems]]
  name = "Pasang Lampu Neon"
  price = "110.000"
[[params.tabelItems]]
  name = "Pasang Lampu Downlight"
  price = "100.000"
[[params.tabelItems]]
  name = "Pasang Lampu Halogen"
  price = "95.000"
[[params.tabelItems]]
  name = "Pasang Lampu Sorot"
  price = "150.000"
[[params.tabelItems]]
  name = "Pasang Panel Box Titik 15 Grup"
  price = "180.000"

[params.appliList]
  "Instalasi Listrik Rumah" = "rumah tinggal, apartemen"
  "Instalasi Listrik Kantor" = "kantor kecil, gedung perkantoran"
  "Instalasi Listrik Ruko" = "ruko, tempat usaha"
  "Perbaikan Instalasi Listrik" = "perbaikan listrik di rumah, kantor"
  "Pemasangan Saklar dan Stop Kontak" = "ruang tamu, ruang kerja, kamar tidur"
  "Pemasangan Panel Listrik" = "rumah besar, kantor, pabrik"
  "Membuat Lubang Stop Kontak" = "persiapan instalasi stop kontak"
  "Membuat Lubang Saklar Single" = "persiapan instalasi saklar"
  "Pembobokan Saklar Seri" = "pembobokan untuk saklar seri"
  "Pembobokan Outlet Telepon" = "persiapan instalasi telepon"
  "Membuat Lubang Outlet Antena" = "persiapan instalasi antena"
  "Membuat Lubang Outlet MCB" = "persiapan untuk pemasangan MCB"
  "Pemasangan Kabel Listrik" = "menyediakan koneksi listrik"
  "Pemasangan Saklar" = "instalasi saklar di berbagai ruangan"
  "Instalasi Saklar AC" = "untuk kontrol AC"
  "Instalasi Stop Kontak Water Heater" = "untuk pemanas air"
  "Pemasangan Lampu" = "penyediaan penerangan"
  "Instalasi Lampu Taman" = "penerangan di luar ruangan"
  "Pemasangan Kabel Antena Layar" = "untuk televisi"
  "Pemasangan Radar Pompa Air" = "untuk pompa air"
  "Instalasi Panel MCB Listrik" = "distribusi listrik yang aman"
  "Pemasangan MCB" = "untuk proteksi sirkuit"
  "Instalasi Kabel Induk" = "untuk distribusi listrik utama"
  "Pasang Lampu Fitting Plafon" = "instalasi lampu plafon"
  "Pasang Lampu Gantung" = "instalasi lampu gantung"
  "Pasang Kipas Angin Gantung" = "instalasi kipas angin"
  "Pasang Exhaust Fan Dinding/Plafon" = "untuk ventilasi"
  "Pasang Lampu Dinding" = "penerangan dinding"
  "Pasang Lampu Neon" = "penerangan ruang"
  "Pasang Lampu Downlight" = "penerangan fokus"
  "Pasang Lampu Halogen" = "penerangan berkualitas tinggi"
  "Pasang Lampu Sorot" = "untuk pencahayaan ekstra"
  "Pasang Panel Box Titik 15 Grup" = "untuk pengaturan listrik"

[params.kegunaanList]
  "Instalasi Listrik Rumah" = "memastikan rumah memiliki instalasi listrik yang aman dan efisien"
  "Instalasi Listrik Kantor" = "menyediakan instalasi listrik profesional untuk gedung perkantoran"
  "Instalasi Listrik Ruko" = "memastikan tempat usaha memiliki listrik yang aman dan handal"
  "Perbaikan Instalasi Listrik" = "mengatasi masalah listrik seperti korsleting dan kerusakan"
  "Pemasangan Saklar dan Stop Kontak" = "memperbarui atau menambah saklar dan stop kontak di berbagai ruangan"
  "Pemasangan Panel Listrik" = "menyediakan distribusi listrik yang aman untuk rumah besar atau gedung"
  "Membuat Lubang Stop Kontak" = "persiapan untuk pemasangan stop kontak"
  "Membuat Lubang Saklar Single" = "persiapan untuk pemasangan saklar"
  "Pembobokan Saklar Seri" = "menyiapkan tempat untuk saklar seri"
  "Pembobokan Outlet Telepon" = "menyiapkan tempat untuk outlet telepon"
  "Membuat Lubang Outlet Antena" = "persiapan untuk outlet antena"
  "Membuat Lubang Outlet MCB" = "persiapan untuk pemasangan MCB"
  "Pemasangan Kabel Listrik" = "menyediakan koneksi listrik yang aman"
  "Pemasangan Saklar" = "memudahkan akses listrik di ruangan"
  "Instalasi Saklar AC" = "pengaturan kontrol AC"
  "Instalasi Stop Kontak Water Heater" = "menyediakan sumber listrik untuk pemanas air"
  "Pemasangan Lampu" = "menyediakan penerangan yang memadai"
  "Instalasi Lampu Taman" = "menambah estetika dan keamanan di luar ruangan"
  "Pemasangan Kabel Antena Layar" = "untuk kebutuhan televisi"
  "Pemasangan Radar Pompa Air" = "menyediakan koneksi untuk pompa air"
  "Instalasi Panel MCB Listrik" = "untuk distribusi listrik yang aman"
  "Pemasangan MCB" = "untuk perlindungan sirkuit listrik"
  "Instalasi Kabel Induk" = "untuk penyambungan listrik utama"
  "Pasang Lampu Fitting Plafon" = "untuk penerangan plafon"
  "Pasang Lampu Gantung" = "untuk penerangan estetis"
  "Pasang Kipas Angin Gantung" = "menyediakan sirkulasi udara"
  "Pasang Exhaust Fan Dinding/Plafon" = "untuk ventilasi yang baik"
  "Pasang Lampu Dinding" = "untuk penerangan di dinding"
  "Pasang Lampu Neon" = "untuk penerangan yang efisien"
  "Pasang Lampu Downlight" = "untuk penerangan fokus di area tertentu"
  "Pasang Lampu Halogen" = "menyediakan pencahayaan berkualitas tinggi"
  "Pasang Lampu Sorot" = "untuk penerangan tambahan"
  "Pasang Panel Box Titik 15 Grup" = "untuk pengaturan sirkuit listrik"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Jasa Instalasi dan Tukang Listrik Berpengalaman | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"